server:
  port: 8081
#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cnlive_oicc?autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root
#mybatis:
  type-aliases-package: com.cnlive.oicc
  thymeleaf:
    cache: false
logging:
  level:
    com.cnlive.oicc.mapper:  debug
#debug: true