server:
  port: 80
#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cnlive_oicc?autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
#mybatis:
  type-aliases-package: com.cnlive.oicc.bean
  thymeleaf:
    cache: false
